export default {
  SEARCH_STUDENT_LIST_BY_OPTION: "SEARCH_STUDENT_LIST_BY_OPTION",

  FETCH_USER_INFO: "FETCH_USER_INFO",
  FETCH_LESSON_INFO: "FETCH_LESSON_INFO",
  FETCH_STUDENT_LIST: "FETCH_STUDENT_LIST",
  FETCH_CLASS_INFO: "FETCH_CLASS_INFO",
  FETCH_LESSON_SATISFIED_INFO: "FETCH_LESSON_SATISFIED_INFO",
  REPLY_USER_FEED_BACK: "REPLY_USER_FEED_BACK",
  FETCH_HOMEWORK: "FETCH_HOMEWORK",
  SWITCH_EXCELLENT_HOMEWORK: "SWITCH_EXCELLENT_HOMEWORK",
  RETURN_BACK_HOMEWORK_COMMENT: "RETURN_BACK_HOMEWORK_COMMENT",
  PUBLISH_COMMENT_TO_HOMEWORK: "PUBLISH_COMMENT_TO_HOMEWORK",
  SEARCH_HOMEWORK_LIST_BY_OPTION: "SEARCH_HOMEWORK_LIST_BY_OPTION",
  SWITCH_CURRENT_TAB: "SWITCH_CURRENT_TAB"
}
